# Generated by Django 4.2.9 on 2024-01-21 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashmon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wifis',
            name='rssi',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
