# Generated by Django 4.2.9 on 2024-03-02 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashmon', '0002_wifis_rssi'),
    ]

    operations = [
        migrations.CreateModel(
            name='PingTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ssid', models.CharField(max_length=100)),
                ('ping_time', models.IntegerField()),
            ],
        ),
    ]
