# Generated by Django 4.2.9 on 2024-03-11 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashmon', '0003_pingtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='wifis',
            name='date_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
