# Generated by Django 4.2.9 on 2024-03-11 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashmon', '0004_wifis_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='pingtime',
            name='ping_date_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
